#coding=utf-8
BOT_NAME = 'Smzdm'

SPIDER_MODULES = ['Smzdm.spiders']
NEWSPIDER_MODULE = 'Smzdm.spiders'

ITEM_PIPELINES=['Smzdm.pipelines.SmzdmPipeline']

#mongodb set
MONGODB_SERVER = 'localhost'
MONGODB_PORT = 27017
MONGODB_DB = 'scrapy'
MONGODB_COLLECTION = 'smzdm'
MONGODB_UNIQ_KEY = 'id'
MONGODB_ITEM_ID_FIELD = '_id'
MONGODB_SAFE = True

#RETRY_ENABLED = False
DOWNLOAD_TIMEOUT = 60
LOG_FILE='smzdy.log'
LOG_LEVEL='INFO'
#REDIRECT_ENABLED = False

#app seting
'''START_URL = ['http://www.liuzhuni.com',
             'http://www.smzdm.com',
             'http://www.zhizhizhi.com',
             'http://zhi.zhe800.com',
             'http://www.91tehui.com']'''
START_URL = ['http://www.liuzhuni.com',
             'http://www.smzdm.com',
             'http://zhi.zhe800.com',
             'http://www.91tehui.com',
             'http://www.tsdxb.com',
             'http://www.huihui.cn/deals',
             'http://www.tz100.com',
             'http://www.kiees.com/?cat=43']
#START_URL = ['http://www.kiees.com/?cat=43']
OUTFILE = 'output_result.json'
CUT_TIME = 3600*24
MAX_ITEM_NUM = 50
URL_TO_NAME = {'http://www.smzdm.com':'SMZDM',
               'http://www.liuzhuni.com' : 'LZN',
               'http://www.zhizhizhi.com' : 'ZZZ',
               'http://zhi.zhe800.com' : 'Z800',
               'http://www.91tehui.com' : '91TH',
               'http://www.tsdxb.com' : 'TSDXB',
               'http://www.huihui.cn/deals' : 'HH',
               'http://www.tz100.com' : 'TZ',
               'http://www.kiees.com/?cat=43' : 'FXZDM'}
PATH_CONFIG={
'NAME_TO_PRE' : {'SMZDM' : 'http://www.smzdm.com',
                 'LZN' : 'http://www.liuzhuni.com',
                 'ZZZ' : 'http://www.zhizhizhi.com',
                 'Z800' : 'http://zhi.zhe800.com',
                 '91TH' : 'http://www.91tehui.com',
                 'TSDXB' : 'http://www.tsdxb.com',
                 'HH' : 'http://www.huihui.cn',
                 'TZ' : 'http://www.tz100.com',
                 'FXZDM' : 'http://www.kiees.com'},
'NAME_TO_SHOW' : {'SMZDM':'什么值得买_www.smzdm.com',
                  'LZN' : '留住你_www.liuzhuni.com',
                  'ZZZ' : '值得买_www.zhizhizhi.com',
                  'Z800' : '折800_www.zhi.zhe800.com',
                  '91TH' : '91特惠_www.91tehui.com',
                  'TSDXB' : '天上掉馅饼_www.tsdxb.com',
                  'HH' : '惠惠_www.huihui.cn/deals',
                  'TZ' : '淘者_www.tz100.com',
                  'FXZDM' : '发现值得买_www.kiees.com'},
'MAIN_PATH' : {'SMZDM':'//div[@class="perContentBox "]',
               'LZN' : '//li[@class="con_list "]',
               'ZZZ' : '//div[@class="list_box_l"]',
               'Z800' : '//div[@class="ztdeal clear "]',
               '91TH' : '//div[@class="list_summary perContentBox"]',
               'TSDXB' : '//div[@class="bkcon"]',
               'HH' : '//li[@class="clearfix "]',
               'TZ' : '//div[@class="cell"]',
               'FXZDM' : '//div[@class="postbox"]'},
'TITLE_PATH' : {'SMZDM':['div/h2[@class="con_title"]/a/@title'],
                'LZN' : ['a/text()'],
                'ZZZ' : ['ul/h2/a/@title'],
                'Z800' : ['h3/span/a/text()'],
                '91TH' : ['div[@class="list_title"]/a/@title','div[@class="list_title"]/a/span/text()'],
                'TSDXB' : ['h2/a/text()','h2/a/span/text()'],
                'HH' : ['h3/a/text()','h4/text()'],
                'TZ' : ['table/tbody/tr/td/h2/a/text()','table/tbody/tr/td/h2/a/span/text()'],
                'FXZDM' : ['div/a/@title']},
'PUB_TIME_PATH' : {'SMZDM' : 'div[@class="dateTime"]/text()',
                   'LZN' : './/span[@class="pub_time"]/text()',
                   'ZZZ' : 'NONE',
                   'Z800' : 'h3/em/text()',
                   '91TH' : 'div[@class="metas"]/span[@class="date"]/text()',
                   'TSDXB' : 'NONE',
                   'HH' : 'NONE',
                   'TZ' : 'NONE',
                   'FXZDM' : 'NONE'},
'PUB_TIME_FORMAT' : {'SMZDM' : '%m-%d %H:%M',
                     'LZN' : '%Y-%m-%d %H:%M:%S',
                     'ZZZ' : 'NONE',
                     'Z800' : '%Y/%m/%d %H:%M',
                     '91TH' : '%Y-%m-%d %H:%M',
                     'TSDXB' : 'NONE',
                     'HH' : 'NONE',
                     'TZ' : 'NONE',
                     'FXZDM' : 'NONE'},
'CONTENT_URL' : {'SMZDM' : 'div/h2[@class="con_title"]/a/@href',
                 'LZN' : 'a/@href',
                 'ZZZ' : 'ul/h2/a/@href',
                 'Z800' : 'h3/span/a/@href',
                 '91TH' : 'div[@class="list_title"]/a/@href',
                 'TSDXB' : 'h2/a/@href',
                 'HH' : 'h3/a/@href',
                 'TZ' : 'table/tbody/tr/td/h2/a/@href',
                 'FXZDM' : 'div/a/@href'},
'NEXT_PAGE' : {'SMZDM' : '//a[@class="pagedown"]/@href',
               'LZN' : '//div[@class="pagination"]/a/@href',
               'ZZZ' : "//a[@class='nextpostslink']/@href",
               'Z800' : '//span[@class="next"]/a/@href',
               '91TH' : '//a[@class="nextpostslink"]/@href',
               'TSDXB' : '//div[@class="pagen"]/a/@href',
               'HH' : '//a[@class="js-log pager-next"]/@href',
               'TZ' : '//a[@class="next"]/@href',
               'FXZDM' : "//a[@class='nextpostslink']/@href"},
'NEXT_PAGE_INDEX' : {'SMZDM' : -1,
                'LZN' : -1,
                'ZZZ' : -1,
                'Z800' : -1,
                '91TH' : -1,
                'TSDXB' : -1,
                'HH' : -1,
                'TZ' : -1,
                'FXZDM' : -1},
'DESC_MAIN_PATH' : {'SMZDM' : '//div[@class="perContentBox"]',
                    'LZN' : '//div[@class="detail_content"]',
                    'ZZZ' : '//div[@class="content"]',
                    'Z800' : '//div[@id="contentA"]',
                    '91TH' : '//div[@class="post_content"]',
                    'TSDXB' : '//div[@class="bkcon"]',
                    'HH' : '//div[@id="item-detail"]',
                    'TZ' : '//div[@id="Content_detail"]',
                    'FXZDM' : '//div[@class="entry lazyload"]'},
'DESC_PATH' : {'SMZDM' : ['//p[@class="p_excerpt"]','//p[@class="p_detail"]'],
               'LZN' : ['//div[@class="detail_inner"]/p'],
               'ZZZ' : ['//div[@class="content_text"]/p'],
               'Z800' : ['//div[@class="info"]/p'],
               '91TH' : ['p'],
               'TSDXB' : ['//div[@class="desc"]/p'],
               'HH' : ['//p[@class="Strategy-indent-p editer-content"]','//p[@class="Strategy-p editer-content"]'],
               'TZ' : ['.//p'],
               'FXZDM' : ['//div[@class="entry-content clearfix"]/p']},
'DESC_LINK_URL' : {'SMZDM' : './/a/@href',
                       'LZN' : './/a/@href',
                       'ZZZ' : './/a/@href',
                       'Z800' : './/a/@href',
                       '91TH' : './/a/@href',
                       'TSDXB' : './/a/@href',
                       'HH' : './/a/@href',
                       'TZ' : './/a/@href',
                       'FXZDM' : './/a/@href'},
'DESC_LINK_CONTENT' : {'SMZDM' : './/a/text()',
                   'LZN' : './/a/text()',
                   'ZZZ' : './/a/text()',
                   'Z800' : './/a/text()',
                   '91TH' : './/a/span/text()',
                   'TSDXB' : './/a/span/text()',
                   'HH' : './/a/text()',
                   'TZ' : './/a/text()',
                   'FXZDM' : './/a/text()'},
'DESC_IMG_PATH' : {'SMZDM' : 'img/@src',
                   'LZN' : 'a/img/@src',
                   'ZZZ' : 'img/@src',
                   'Z800' : 'NONE',
                   '91TH' : 'img/@src',
                   'TSDXB' : 'NONE',
                   'HH' : 'NONE',
                   'TZ' : 'NONE',
                   'FXZDM' : 'a/img/@src'},
'GO_LINK_PATH' : {'SMZDM' : ['//div[@class="zhida"]/a/@href','//div[@class="zhida_more"]/a/@href','//div[@class="zhida_more"]/div/a/@href'],
                 'LZN' : ['//a[@class="goto_link"]/@href'],
                 'ZZZ' : ['//div[@class="content_box_gobuy"]/a/@href'],
                 'Z800' : ['.//div[@class="l"]/span/a/@href'],
                 '91TH' : ['//div[@class="buy"]/a/@href'],
                 'TSDXB' : ['//div[@class="wzcon"]/a/@href'],
                 'HH' : ['//div[@class="huili-relevant-left"]/a/@href'],
                 'TZ' : ['//a[@class="btn_buy"]/@href'],
                 'FXZDM' : ['//div[@id="shop_url"]/a/@href']},
'IMG_PATH' : {'SMZDM' : 'NONE',
              'LZN' : 'NONE',
              'ZZZ' : 'NONE',
              'Z800' : '//div[@class="info"]/img/@src',
              '91TH' : 'NONE',
              'TSDXB' : '//div[@class="img"]/a/img/@src',
              'HH' : '//div[@class="Strategy-pic"]/img/@src',
              'TZ' : '//a[@class="post_thumb_pic"]/img/@src',
              'FXZDM' : 'NONE'},
'CAT_PATH' : {'SMZDM' : '//div[@class="classified"]/a/text()',
              'LZN' : '//div[@class="other_info"]/a[@class="pub_cat"]/text()',
              'ZZZ' : '//a[@rel="category tag"]/text()',
              'Z800' : './/div[@class="r"]/h4/a/text()',
              '91TH' : '//span[@class="cates"]/a/text()',
              'TSDXB' : '//div[@class="bt1"]/div/a/text()',
              'HH' : '//a[@class="hico-doc hico-cagegory js-log"]/text()',
              'TZ' : '//div[@class="tags clearfix"]/a/text()',
              'FXZDM' : 'NONE'},
'SOURCE_PATH' : {'SMZDM' : './/span[@class="from_val"]/text()',
                 'LZN' : '//div[@class="other_info"]/a[@class="pub_shop"]/text()',
                 'ZZZ' : 'NONE',
                 'Z800' : 'h3/span/a/text()',
                 '91TH' : "//div[@class='mall']/a/text()",
                 'TSDXB' : '//div[@class="bt1"]/div/a/text()',
                 'HH' : 'NONE',
                 'TZ' : '//span[@class="created"]/a/text()',
                 'FXZDM' : 'NONE'},
'WORTH_SCORE_PATH' : {'SMZDM' : '//div[@class="worth_1"]/a/text()',
                      'LZN' : '//span[@class="worth_num"]/text()',
                      'ZZZ' : 'NONE',
                      'Z800' : 'NONE',
                      '91TH' : '//span[@class="vote_up"]/a/span/text()',
                      'TSDXB' : 'NONE',
                      'HH' : 'NONE',
                      'TZ' : 'NONE',
                      'FXZDM' : 'NONE'},
'BAD_SCORE_PATH' : {'SMZDM' : '//div[@class="worth_3"]/a/text()',
                    'LZN' : '//span[@class="noworth_num"]/text()',
                    'ZZZ' : 'NONE',
                    'Z800' : 'NONE',
                    '91TH' : '//span[@class="vote_down"]/a/span/text()',
                    'TSDXB' : 'NONE',
                    'HH' : 'NONE',
                    'TZ' : 'NONE',
                    'FXZDM' : 'NONE'},
'NEED_FILTER' : {'SMZDM':1,
                 'LZN':1,
                 'ZZZ':0,
                 'Z800':0,
                 '91TH':1,
                 'TSDXB' : 0,
                 'HH' : 0,
                 'TZ' : 0,
                 'FXZDM' : 0}
}
# Crawl responsibly by identifying yourself (and your website) on the user-agent
#USER_AGENT = 'Smzdm (+http://www.yourdomain.com)'
